# Generated by Django 2.2 on 2019-05-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedregion',
            name='projected_srid',
            field=models.IntegerField(default=3857),
        ),
    ]
