# Generated by Django 2.1.5 on 2019-01-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_sent_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
