# Generated by Django 2.2 on 2019-06-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190616_1913'),
        ('rundezvous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='country',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.State', verbose_name='last known state'),
        ),
    ]
