# Generated by Django 2.1.5 on 2019-01-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'Site User', 'verbose_name_plural': 'Site Users'},
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='active_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_participants', to='chat.ChatRoom'),
        ),
    ]
