# Generated by Django 2.2 on 2019-05-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rundezvous',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='rundezvous',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chatroom', serialize=False, to='rundezvous.Rundezvous'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rundezvous.Chatroom'),
        ),
    ]
