# Generated by Django 2.2 on 2019-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='rundezvous',
            new_name='rundezvouses',
        ),
    ]
