# Generated by Django 2.2 on 2019-05-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0002_auto_20190526_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rundezvous',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rundezvous.Rundezvous'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
