# Generated by Django 2.1.5 on 2019-01-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0002_auto_20190120_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='active_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.ChatRoom'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
