# Generated by Django 2.2 on 2019-05-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0003_auto_20190526_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='rundezvous_status',
            new_name='status',
        ),
    ]
