# Generated by Django 2.1.5 on 2019-01-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('rundezvous', '0004_auto_20190120_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='last_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.SupportedRegion'),
        ),
    ]
