# Generated by Django 2.2 on 2019-05-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0004_auto_20190526_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertorundezvous',
            options={'verbose_name': 'user to rundezvous', 'verbose_name_plural': 'user to rundezvouses'},
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
