# Generated by Django 2.2 on 2019-06-14 01:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rundezvous', '0005_auto_20190527_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundezvous',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertorundezvous',
            name='meetup_decision',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='rundezvous',
            name='expiration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AlterField(
            model_name='rundezvous',
            name='landmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Landmark'),
        ),
        migrations.AlterField(
            model_name='rundezvous',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Looking'), ('C', 'Chatting'), ('R', 'Running'), ('V', 'Review')], default='N', max_length=1),
        ),
    ]
